bin/fmt fixes

diff --git a/bin/fmt b/bin/fmt
--- a/bin/fmt
+++ b/bin/fmt
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
 # DOC: Format terraform, python, and shell script files.
 
@@ -6,14 +6,16 @@ if which -s terraform; then
   echo "Formatting Terraform files"
   terraform fmt -recursive -write
 else
-  echo "Terraform not found. Skipping."
+  echo "Can not find the terraform binary. Please install Terraform first."
+  exit 1
 fi
 
 if which -s shfmt; then
   echo "Formatting shell scripts"
   shfmt -bn -ci -i 2 -w -l $(shfmt -f .)
 else
-  echo "Shfmt not found. Skipping."
+  echo "Could not find the shfmt binary. Please install shfmt first."
+  exit 1
 fi
 
 if which -s yapf; then
@@ -25,5 +27,6 @@ if which -s yapf; then
     --recursive \
     .
 else
-  echo "Yapf not found. Skipping."
+  echo "Could not find yapf. Please install it first."
+  exit 1
 fi
