add option to pass in snapshot tag for server var autogeneration (#203)

diff --git a/cloud/shared/bin/run b/cloud/shared/bin/run
--- a/cloud/shared/bin/run
+++ b/cloud/shared/bin/run
@@ -13,6 +13,9 @@
 # install the package and activate the venv. The activation has to happen in the
 # parent process before the python code is run.
 # This is why we need a bash script that preceeds the python code
+set -e
+set -o pipefail
+
 source cloud/shared/bin/python_env_setup
 
 # Get the arguments that we want to pass to run.py
@@ -27,6 +30,19 @@ while getopts s:c:t: flag; do
   esac
 done
 
+# if the tag is "latest", resolve it to the specific snapshot tag from Docker
+if [[ "${tag}" == "latest" ]]; then
+  docker pull --platform linux/x86_64 docker.io/civiform/civiform:latest
+  snapshot_tag="$(docker inspect docker.io/civiform/civiform:latest \
+    | grep 'CIVIFORM_IMAGE_TAG' \
+    | grep -oE 'SNAPSHOT-\w+-\d+')"
+  if [[ -z "${snapshot_tag}" ]]; then
+    echo "Latest snapshot tag not found." 2>&1
+    exit 1
+  fi
+  tag="${snapshot_tag}"
+fi
+
 #######################################
 # Get the value in a JSON document at the given URL.
 # Arguments:
@@ -36,24 +52,25 @@ done
 #   Value found at the specified path in the JSON document
 #######################################
 function fetch_json_val() {
-  curl -s "${1}" \  \
+  curl -s "${1}" \
     | python3 -c "import sys, json; print(json.load(sys.stdin)${2})"
 }
 
-# Reassign tag to version so we don't overwrite tag
-version=${tag}
-# If version is "latest" get the latest release number (eg. v1.26.0)
-if [[ ${version} == "latest" ]]; then
-  version=$(fetch_json_val \
-    "https://api.github.com/repos/civiform/civiform/releases/latest" \
-    "['tag_name']")
-fi
+commit_sha=""
 
-# Get the commit sha for the commit at the tip of the CiviForm version being deployed
-tag_url=$(fetch_json_val \
-  "https://api.github.com/repos/civiform/civiform/git/refs/tags/${version}" \
-  "['object']['url']")
-commit_sha=$(fetch_json_val ${tag_url} "['object']['sha']")
+if [[ "${tag}" == "SNAPSHOT"* ]]; then
+  # In a snapshot tag, eg. "SNAPSHOT-920bc49-1685642238", the middle section is the
+  # shortened commit sha. Use this to get the full commit sha.
+  split_tag=(${tag//-/ })
+  short_sha=${split_tag[1]}
+  commit_sha=$(fetch_json_val "https://api.github.com/repos/civiform/civiform/commits/${short_sha}" "['sha']")
+else
+  # tag is a specific version of CiviForm (eg. v1.2.3), get the commit sha at the tip of that version
+  tag_url=$(fetch_json_val \
+    "https://api.github.com/repos/civiform/civiform/git/refs/tags/${tag}" \
+    "['object']['url']")
+  commit_sha=$(fetch_json_val ${tag_url} "['object']['sha']")
+fi
 
 dependencies_file_path="cloud/shared/bin/env-var-docs-python-dependencies.txt"
 
