playing with docker fetch

diff --git a/cloud/shared/bin/run b/cloud/shared/bin/run
--- a/cloud/shared/bin/run
+++ b/cloud/shared/bin/run
@@ -13,6 +13,8 @@
 # install the package and activate the venv. The activation has to happen in the
 # parent process before the python code is run.
 # This is why we need a bash script that preceeds the python code
+set -e
+set -o pipefail
 
 source cloud/shared/bin/python_env_setup
 
@@ -28,6 +30,19 @@ while getopts s:c:t: flag; do
   esac
 done
 
+# if the tag is "latest", resolve it to the specific snapshot tag from Docker
+if [[ "${tag}" == "latest" ]]; then
+  docker pull --platform linux/x86_64 docker.io/civiform/civiform:latest
+  snapshot_tag="$(docker inspect docker.io/civiform/civiform:latest \
+    | grep 'CIVIFORM_IMAGE_TAG' \
+    | grep -oE 'SNAPSHOT-\w+-\d+')"
+  if [[ -z "${snapshot_tag}" ]]; then
+    echo "Latest snapshot tag not found." 2>&1
+    exit 1
+  fi
+  tag="${snapshot_tag}"
+fi
+
 #######################################
 # Get the value in a JSON document at the given URL.
 # Arguments:
@@ -37,16 +52,13 @@ done
 #   Value found at the specified path in the JSON document
 #######################################
 function fetch_json_val() {
-  curl -s "${1}" \  \
+  curl -s "${1}" \
     | python3 -c "import sys, json; print(json.load(sys.stdin)${2})"
 }
 
 commit_sha=""
 
-if [[ "${tag}" == "latest" ]]; then
-  # If tag is "latest" get the commit sha from the tip of main
-  commit_sha=$(fetch_json_val "https://api.github.com/repos/civiform/civiform/branches/main" "['commit']['sha']")
-elif [[ "${tag}" == *"SNAPSHOT"* ]]; then
+if [[ "${tag}" == "SNAPSHOT"* ]]; then
   # In a snapshot tag, eg. "SNAPSHOT-920bc49-1685642238", the middle section is the
   # shortened commit sha. Use this to get the full commit sha.
   split_tag=(${tag//-/ })
